### ISSUE TITLE
The great "Lets not crash tbh fam" plan

### ISSUE THREAD

**Issue by PinkishCow** [BryceMatthes/betterdgg#26]
As the title suggests, lets not crash on every little thing that happens, literally nothing in in the extension has exception handling and that's not good as proven by today's events(Sorry BTW). So we need to decide on how we are going to handle chat not loading and stuff within the extension breaking, such as one **giant** try catch with a console log and an alert with a link to the wiki page(sadly you cant put hyperlinks in HTML alerts) or actually put effort into it and see if we cant handle stuff properly and fix it when it breaks. 
- [x] Add code to stop one error crashing whole extension
- [ ] Add error messages

:+1:

**Comment by kenany** [comment]
> If you need to globally trap content script errors, your best bet is to assume `window.onerror` is busted for now in content scripts. Instead, wrap all Javascript code in try-catch blocks, which gives you access to useful error information.

http://stackoverflow.com/a/31214372

:/

**Comment by PinkishCow** [comment]
RIP, last comment on that chrome bug was in december and that was asking if anything had been done yet.

**Comment by kenany** [comment]
This might allow one module to fail whilst keeping others functional. Not tested at all.

``` js
for (var module in window.BetterDGG) {
    if (window.BetterDGG[module].init) {
        try {
            window.BetterDGG[module].init();
        }
        catch (e) {
            // display error somewhere and say that it is from `module`
        }
    }
}
```

**Comment by PinkishCow** [comment]
That seems better than what i had done, its hard to test if it works when chat is not broken. 

``` javascript
if (typeof(destiny.chat) != undefined) {
    for (var module in window.BetterDGG) {
        if (window.BetterDGG[module].init) {
            window.BetterDGG[module].init();
        }
    }
} else {
    alert("Error m8")
}
```

**Comment by downthecrop** [comment]
Merged this in. Still need to copy the line that loads settings first.

Edit: Merged a pull that did this.

**Comment by kenany** [comment]
I said this in chat but I'll repeat it here (and expand upon it) so that it doesn't get lost:

Nicest solution we might have is, on error, to try and show a jade popup linking to [troubleshooting](https://github.com/BryceMatthes/betterdgg/wiki/Troubleshooting) and displaying:
- the error stack trace
- the user's settings
- the module that caused it

for the user to copy-paste into pastebin and link to us. If showing the jade popup fails too, then we `alert()` saying that something went terribly wrong in loading _module_ and that we need a screenshot of the console.

I don't know if we need to do the `destiny.chat`-is-defined check because, especially after https://github.com/BryceMatthes/betterdgg/pull/24, `destiny.chat` _should_ never be `undefined`. Even if it is, [our current try-catch](https://github.com/BryceMatthes/betterdgg/blob/26a1728f032e4bf87032a09aea15229557d29d1e/betterdgg/betterdgg.js#L6-L11) would catch the numerous errors that would arise from such an event. Also, on that note, we should ensure that if multiple modules fail we ideally only display one popup (the first, most likely).

**Comment by downthecrop** [comment]
I completely agree with @KenanY . A jade popup with some info for troubleshooting as default and a standard alert() showing additional information + console.log would probably be best I think.

**Comment by xDashh** [comment]
One problem that I see is that you cannot easily distinguish between errors that are "urgent" (break everything) and problems like in #35 that have been in the addon for a long time (I assume) but don't really have any impact on the user. For something like this a popup would be too much (since again, the user doesn't really care). Maybe we can find a middle way between `console.log()` and a popup?

**Comment by PinkishCow** [comment]
Possibly we could decide what things are extention breaking like settings.js throwing an error and what things are not that bad like passivestalk.js breaking, then use error.alert and error.important for different things to decide if we make a popup or we just make a chat alert like "Passive stalk has encountered an error and will not work"
