### ISSUE TITLE
Double-click to open logs

### ISSUE THREAD

**Issue by vaindil** [BryceMatthes/betterdgg#79]
I don't want to submit a pull request for this unless it's decided this is a good thing to add, so I'm doing this issue instead.

I wrote [a user script](https://greasyfork.org/en/scripts/25217-destiny-gg-bigscreen-improvements) for myself and a friend that does a couple miscellaneous things, but the one I really use is double-clicking a username to open a user's logs. I'm sure double-click wouldn't be ideal for all users, there would definitely be complaints about it being triggered too much, but I think the core code is at least decent enough to be worked with.

The rest of this is the code and explanation. I'm happy to tweak it however necessary if you'd like it included.

---

This disaster is used because chat is an iframe and it's pretty difficult to manipulate that content from a user script. This block runs when the chat frame is fully loaded and binds to its `body`, using `.on()` to bind to all current and future matched elements. The first statement handles actual usernames (authors), the second does usernames in messages, and the third handles the automated "X muted/banned by Bot" messages.

```js
var cmdMsgRegex = /([a-zA-Z0-9_]+) (?:muted|banned) by Bot/;

$('#chat-frame').load(function() {

    $('body', $('#chat-frame').contents()).on('dblclick', 'a.user', function(event) {
        window.open('https://dgg.overrustlelogs.net/' + event.target.parentElement.dataset.username, '_blank');
    });

    $('body', $('#chat-frame').contents()).on('dblclick', 'span.chat-user', function(event) {
        window.open('https://dgg.overrustlelogs.net/' + event.target.innerText, '_blank');
    });

    $('body', $('#chat-frame').contents()).on('dblclick', 'div.command-msg span.msg', function(event) {
        var res = cmdMsgRegex.exec(event.target.innerText);
        if (res !== null) {
            window.open('https://dgg.overrustlelogs.net/' + res[1], '_blank');
        }

    });
});
```

---

I have the user script set to run on multiple domains (bigscreen and logs), so this code only runs if a) the user is actually on the logs site, and b) they were sent there from bigscreen. (I haven't added overrustle yet as we don't really use it.) If those conditions are met, the page scrolls to the very bottom. The logs site loads in a way that isn't really easy to attach a listener to, so I just watch `body` for changes and scroll down each time a `span` is added within the content `div`. (Not a problem at this point since the page is static once the content is initially loaded.)

```js
if (document.domain === 'dgg.overrustlelogs.net') {
    if (document.referrer && (document.referrer.match(/:\/\/(.[^/]+)/)[1] === 'www.destiny.gg')) {
        var logsObserver = new MutationObserver(scrollOnLogs);
        logsObserver.observe(document.body, {
            childList: true,
            subtree: true
        });
    }
    return;
}

function scrollOnLogs(records, mutationObserver) {
    records.forEach(function(el) {
        if (el.addedNodes[0] && el.addedNodes[0].tagName === 'SPAN' && el.addedNodes[0].parentNode && el.addedNodes[0].parentNode.className === 'text') {
            window.scrollTo(0, document.body.scrollHeight);
        }
    });
}
```

**Comment by PinkishCow** [comment]
This is a great idea because I sincerely hope everyone who uses one of them shit chat commands for logs/bot/opbot gets slapped with a really heavy object because they do nothing but shit up chat to save themselves 2 seconds of time where they can't sperg out all over chat.(Obviously there are exceptions where it is used well and all bots serve their purpose to some degree) Sadly I wouldn't like it being done this way.

Personally I feel a "/logs" command would be if not just a better fit due to /stalk being a thing for stuff in upto the last 50 lines, a better fit for a chat filled with braindead retards. Even with a setting there will be people misclicking them constantly, and different keys don't bode well either. Double left click will miss 9/10 times for 90% of the chat room(The spastics), middle click is for scrolling, and right click is just a right click, can't do fuck with that. 

Also implementation of the command version would be much easier as it's just the command regex bollocks to ChatInfoMessage with the dgg overrustle logs thing then the name twatted on the end.

Other people may have other opinions and its @BryceMatthes decision in the end though obviously.

Klappa tho 👏  ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️ ❤️

**Comment by vaindil** [comment]
Yeah, I agree that double-click is a mess, I wrote it that way because my friend and I prefer it, but for the wider community it's obviously not great. (We just scroll up once to pause chat and you can double-click easily, but again, not ideal.) I'm open to whatever ideas there are.

**Comment by downthecrop** [comment]
I'm in for /logs and /mentions

**Comment by 9inevolt** [comment]
👍 

/stalk could probably drop the logs link in chat too if you wanted to have one less command.

**Comment by PinkishCow** [comment]
^ Add the logs link into /stalk and add /mentions possibly?

I think mentions are generated only when they are asked for like plots are so someone will have to give overpowered or whoever a shout maybe

**Comment by downthecrop** [comment]
I forgot to close this but in https://github.com/BryceMatthes/betterdgg/commit/5d6ba1628adb2a427690218345ec99cebea38f82 I have added a link to OverRustleLogs with /stalk and integrated the Polecat mentions API.
