### ISSUE TITLE
Chat stops moving and I have to type to reconnect. Disabling BBD.GG fixes this.

### ISSUE THREAD

**Issue by GravitySalad** [BryceMatthes/betterdgg#81]
http://i.imgur.com/rlHxCoK.png

**Comment by PinkishCow** [comment]
That's called disconnecting from chat,  that's just what happens,  you got lucky by it not happening when bbdgg was off

**Comment by GravitySalad** [comment]
It happened multiple times before i disabled bbd.gg, Probably 10-20 times. I must have gotten pretty lucky.

**Comment by PinkishCow** [comment]
Well yeah. And you know why I know this? It's because that's what happens when I restart my router, or my internet drops, or the power fluctuates and knocks out my router but not the pc, or that time just 3 days ago when the fuse went in my extension lead but I didn't notice because chat did not attempt to reconnect itself until I typed in it to meme 🅓🅔🅐🅓🅒🅗🅐🅣
 👌
